CLASSES = {
    "knight": {
        "name": "Knight",
        "icon": "🛡️",
        "desc": "Máu cao, thủ tốt, dễ chơi.",
        "max_hp": 120,
        "max_stamina": 80,
        "attack": 12,
        "defense": 9,
        "crit": 5,
        "weapon": "rusty_sword",
        "armor": "worn_armor",
    },
    "rogue": {
        "name": "Rogue",
        "icon": "🗡️",
        "desc": "Nhanh, chí mạng cao, nhưng máu thấp.",
        "max_hp": 90,
        "max_stamina": 115,
        "attack": 11,
        "defense": 5,
        "crit": 16,
        "weapon": "grave_dagger",
        "armor": "traveler_cloak",
    },
    "mage": {
        "name": "Mage",
        "icon": "🔮",
        "desc": "Kỹ năng mạnh, phòng thủ yếu.",
        "max_hp": 82,
        "max_stamina": 95,
        "attack": 15,
        "defense": 4,
        "crit": 8,
        "weapon": "apprentice_staff",
        "armor": "traveler_cloak",
    },
}

ITEMS = {
    # Weapons
    "rusty_sword": {
        "name": "Rusty Sword",
        "icon": "⚔️",
        "type": "weapon",
        "rarity": "common",
        "attack": 6,
        "defense": 0,
        "crit": 0,
        "desc": "Một thanh kiếm gỉ từng thuộc về lính canh mộ.",
    },
    "grave_dagger": {
        "name": "Grave Dagger",
        "icon": "🗡️",
        "type": "weapon",
        "rarity": "uncommon",
        "attack": 5,
        "defense": 0,
        "crit": 7,
        "desc": "Dao găm mỏng, nhẹ, thích hợp cho đòn chí mạng.",
    },
    "apprentice_staff": {
        "name": "Apprentice Staff",
        "icon": "🪄",
        "type": "weapon",
        "rarity": "uncommon",
        "attack": 8,
        "defense": 0,
        "crit": 2,
        "desc": "Gậy phép cũ, vẫn còn vài tia ma lực yếu ớt.",
    },
    "graveborn_blade": {
        "name": "Graveborn Blade",
        "icon": "🗡️",
        "type": "weapon",
        "rarity": "rare",
        "attack": 13,
        "defense": 0,
        "crit": 5,
        "desc": "Lưỡi kiếm sinh ra từ hầm mộ, lạnh như tiếng chuông tang.",
    },
    "moonlit_staff": {
        "name": "Moonlit Staff",
        "icon": "🌙",
        "type": "weapon",
        "rarity": "epic",
        "attack": 18,
        "defense": 0,
        "crit": 6,
        "desc": "Gậy phép được tắm trong ánh trăng lạnh của khu rừng đen.",
    },

    # Armor
    "worn_armor": {
        "name": "Worn Armor",
        "icon": "🥋",
        "type": "armor",
        "rarity": "common",
        "attack": 0,
        "defense": 5,
        "crit": 0,
        "desc": "Bộ giáp mòn nhưng vẫn tốt hơn da thịt trần.",
    },
    "traveler_cloak": {
        "name": "Traveler Cloak",
        "icon": "🧥",
        "type": "armor",
        "rarity": "uncommon",
        "attack": 0,
        "defense": 3,
        "crit": 4,
        "desc": "Áo choàng nhẹ cho kẻ thích né hơn đỡ.",
    },

    # Rings
    "ring_of_embers": {
        "name": "Ring of Embers",
        "icon": "💍",
        "type": "ring",
        "rarity": "rare",
        "attack": 2,
        "defense": 2,
        "crit": 2,
        "desc": "Chiếc nhẫn ấm lên khi chủ nhân cận kề cái chết.",
    },

    # Consumables
    "healing_herb": {
        "name": "Healing Herb",
        "icon": "🌿",
        "type": "consumable",
        "rarity": "common",
        "heal": 30,
        "desc": "Hồi 30 HP.",
    },
    "ember_flask": {
        "name": "Ember Flask",
        "icon": "🧪",
        "type": "consumable",
        "rarity": "rare",
        "heal_percent": 0.40,
        "desc": "Hồi 40% HP tối đa. Số lần dùng được nạp lại khi nghỉ.",
    },

    # Materials
    "grave_bone": {
        "name": "Grave Bone",
        "icon": "🦴",
        "type": "material",
        "rarity": "common",
        "desc": "Xương cũ dùng trong rèn cấp thấp.",
    },
    "iron_shard": {
        "name": "Iron Shard",
        "icon": "⛓️",
        "type": "material",
        "rarity": "common",
        "desc": "Mảnh sắt dùng để nâng cấp +1 và +2.",
    },
    "ash_fang": {
        "name": "Ash Fang",
        "icon": "🦷",
        "type": "material",
        "rarity": "uncommon",
        "desc": "Răng nanh phủ tro, còn hơi ấm.",
    },
    "blackroot_leaf": {
        "name": "Blackroot Leaf",
        "icon": "🍃",
        "type": "material",
        "rarity": "uncommon",
        "desc": "Lá cây từ khu rừng đen.",
    },
    "ember_stone": {
        "name": "Ember Stone",
        "icon": "🔥",
        "type": "material",
        "rarity": "rare",
        "desc": "Đá lửa cổ dùng để nâng cấp +3 trở lên.",
    },
    "ancient_core": {
        "name": "Ancient Core",
        "icon": "💠",
        "type": "material",
        "rarity": "epic",
        "desc": "Lõi cổ đại dùng cho trang bị cấp cao.",
    },
    "keeper_core": {
        "name": "Keeper Core",
        "icon": "👁️",
        "type": "material",
        "rarity": "epic",
        "desc": "Lõi của kẻ giữ mộ đầu tiên. Nó vẫn nhìn lại bạn.",
    },
}

AREAS = {
    "ember_shrine": {
        "name": "Ember Shrine",
        "icon": "🔥",
        "level": 1,
        "desc": "Đền thờ tàn tro, nơi ngọn lửa yếu ớt vẫn còn thở.",
        "enemies": [],
        "boss": None,
        "unlock": "Khu vực khởi đầu.",
    },
    "forgotten_catacomb": {
        "name": "Forgotten Catacomb",
        "icon": "🪦",
        "level": 1,
        "desc": "Hầm mộ cổ nơi tiếng xương va vào đá vang lên dưới bóng tối.",
        "enemies": ["hollow_rat", "grave_skeleton", "hollow_soldier", "ash_hound"],
        "boss": "keeper_first_grave",
        "unlock": "Mở sẵn sau khi tạo nhân vật.",
    },
    "blackroot_forest": {
        "name": "Blackroot Forest",
        "icon": "🌲",
        "level": 4,
        "desc": "Khu rừng nơi rễ cây uống máu và lá cây thì thầm tên người chết.",
        "enemies": ["thorn_wolf", "lost_hunter", "root_witch"],
        "boss": "weeping_treant",
        "unlock": "Đánh bại Keeper of the First Grave.",
    },
}

ENEMIES = {
    "hollow_rat": {
        "name": "Hollow Rat",
        "icon": "🐀",
        "hp": 26,
        "attack": 6,
        "defense": 1,
        "xp": 8,
        "souls": 18,
        "gold": 6,
        "loot": [("grave_bone", 0.65, 1, 2), ("healing_herb", 0.25, 1, 1)],
    },
    "grave_skeleton": {
        "name": "Grave Skeleton",
        "icon": "💀",
        "hp": 38,
        "attack": 8,
        "defense": 3,
        "xp": 14,
        "souls": 30,
        "gold": 9,
        "loot": [("grave_bone", 0.80, 1, 3), ("iron_shard", 0.35, 1, 1), ("rusty_sword", 0.08, 1, 1)],
    },
    "hollow_soldier": {
        "name": "Hollow Soldier",
        "icon": "🧟",
        "hp": 50,
        "attack": 10,
        "defense": 5,
        "xp": 20,
        "souls": 42,
        "gold": 14,
        "loot": [("iron_shard", 0.55, 1, 2), ("worn_armor", 0.10, 1, 1), ("ember_stone", 0.05, 1, 1)],
    },
    "ash_hound": {
        "name": "Ash Hound",
        "icon": "🐺",
        "hp": 42,
        "attack": 12,
        "defense": 2,
        "xp": 18,
        "souls": 38,
        "gold": 12,
        "loot": [("ash_fang", 0.55, 1, 2), ("healing_herb", 0.20, 1, 1), ("grave_dagger", 0.07, 1, 1)],
    },
    "thorn_wolf": {
        "name": "Thorn Wolf",
        "icon": "🐺",
        "hp": 64,
        "attack": 16,
        "defense": 5,
        "xp": 34,
        "souls": 70,
        "gold": 22,
        "loot": [("blackroot_leaf", 0.70, 1, 2), ("iron_shard", 0.50, 1, 2)],
    },
    "lost_hunter": {
        "name": "Lost Hunter",
        "icon": "🏹",
        "hp": 72,
        "attack": 17,
        "defense": 7,
        "xp": 42,
        "souls": 82,
        "gold": 30,
        "loot": [("iron_shard", 0.65, 1, 3), ("ember_stone", 0.12, 1, 1)],
    },
    "root_witch": {
        "name": "Rootbound Witch",
        "icon": "🧙",
        "hp": 66,
        "attack": 20,
        "defense": 4,
        "xp": 45,
        "souls": 95,
        "gold": 26,
        "loot": [("blackroot_leaf", 0.75, 1, 3), ("apprentice_staff", 0.08, 1, 1), ("ember_stone", 0.15, 1, 1)],
    },
}

BOSSES = {
    "keeper_first_grave": {
        "name": "Keeper of the First Grave",
        "icon": "👑",
        "hp": 260,
        "attack": 18,
        "defense": 8,
        "xp": 120,
        "souls": 280,
        "gold": 80,
        "unlock_area": "blackroot_forest",
        "pattern": ["slash", "summon", "charge", "grave_cleave", "recover"],
        "loot": [("ember_stone", 1.00, 1, 2), ("keeper_core", 1.00, 1, 1), ("graveborn_blade", 0.35, 1, 1)],
    },
    "weeping_treant": {
        "name": "The Weeping Treant",
        "icon": "🌳",
        "hp": 420,
        "attack": 26,
        "defense": 12,
        "xp": 260,
        "souls": 620,
        "gold": 160,
        "unlock_area": None,
        "pattern": ["root_lash", "poison_mist", "charge", "crushing_branch", "recover"],
        "loot": [("ancient_core", 1.00, 1, 1), ("blackroot_leaf", 1.00, 3, 6), ("moonlit_staff", 0.25, 1, 1)],
    },
}

UPGRADE_RULES = {
    1: {"souls": 50, "materials": {"iron_shard": 2}, "chance": 1.00},
    2: {"souls": 120, "materials": {"iron_shard": 4}, "chance": 1.00},
    3: {"souls": 250, "materials": {"ember_stone": 1}, "chance": 1.00},
    4: {"souls": 500, "materials": {"ember_stone": 2}, "chance": 0.85},
    5: {"souls": 1000, "materials": {"ancient_core": 1}, "chance": 0.70},
}

LORE_FRAGMENTS = [
    "Người hành hương mù từng nói: 'Ngọn lửa không chết. Nó chỉ học cách nói dối.'",
    "Trên tường đá có dòng chữ: 'Đừng tin chiếc chuông dưới hầm mộ.'",
    "Bạn tìm thấy mảnh giấy cháy dở: 'Nhà vua không bị giết. Ông ta tự khóa mình trong tro.'",
    "Một tượng đá cụt đầu nắm chặt thanh kiếm. Dưới chân khắc: 'Kẻ giữ mộ đầu tiên không phải người đầu tiên chết.'",
]

# ============================================================
# v0.4 ECONOMY / DAILY / DUNGEON DATA
# ============================================================

ITEMS.update({
    "stamina_draught": {
        "name": "Stamina Draught",
        "icon": "🍵",
        "type": "consumable",
        "rarity": "common",
        "stamina": 35,
        "desc": "Hồi 35 stamina.",
    },
    "camp_kit": {
        "name": "Camp Kit",
        "icon": "⛺",
        "type": "consumable",
        "rarity": "uncommon",
        "heal_percent": 0.25,
        "stamina_percent": 0.25,
        "desc": "Hồi 25% HP và 25% stamina. Dùng để đi đường dài.",
    },
    "ashen_token": {
        "name": "Ashen Token",
        "icon": "🪙",
        "type": "material",
        "rarity": "rare",
        "desc": "Token nhận từ daily/dungeon, dùng cho hệ thống event sau này.",
    },
    "hunter_mark": {
        "name": "Hunter's Mark",
        "icon": "🎯",
        "type": "material",
        "rarity": "uncommon",
        "desc": "Dấu ấn chứng minh bạn đã săn quái trong ngày.",
    },
})

SHOP_ITEMS = [
    {"id": 1, "key": "healing_herb", "quantity": 3, "gold": 45, "label": "Gói hồi máu cơ bản"},
    {"id": 2, "key": "stamina_draught", "quantity": 2, "gold": 55, "label": "Gói hồi stamina"},
    {"id": 3, "key": "iron_shard", "quantity": 4, "gold": 100, "label": "Nguyên liệu nâng cấp cấp thấp"},
    {"id": 4, "key": "ember_stone", "quantity": 1, "gold": 250, "label": "Nguyên liệu hiếm"},
    {"id": 5, "key": "camp_kit", "quantity": 1, "gold": 120, "label": "Bộ cắm trại"},
]

DAILY_REWARD = {
    "souls": 120,
    "gold": 80,
    "items": {"healing_herb": 2, "iron_shard": 2, "ashen_token": 1},
}

DAILY_QUEST_TEMPLATES = [
    {
        "id": "kill_5",
        "name": "Dọn sạch bóng tối",
        "desc": "Đánh bại 5 quái thường.",
        "type": "kill",
        "target": 5,
        "reward_souls": 160,
        "reward_gold": 70,
        "reward_items": {"hunter_mark": 1},
    },
    {
        "id": "explore_3",
        "name": "Bước chân trong tro",
        "desc": "Khám phá 3 lần.",
        "type": "explore",
        "target": 3,
        "reward_souls": 90,
        "reward_gold": 50,
        "reward_items": {"healing_herb": 1},
    },
    {
        "id": "merge_1",
        "name": "Thép biết hát",
        "desc": "Merge/nâng cấp trang bị 1 lần.",
        "type": "merge",
        "target": 1,
        "reward_souls": 120,
        "reward_gold": 60,
        "reward_items": {"iron_shard": 2},
    },
    {
        "id": "dungeon_1",
        "name": "Đi sâu hơn bóng tối",
        "desc": "Hoàn thành 1 dungeon encounter.",
        "type": "dungeon",
        "target": 1,
        "reward_souls": 220,
        "reward_gold": 90,
        "reward_items": {"ashen_token": 1},
    },
]

DUNGEONS = {
    "grave_trial": {
        "name": "Grave Trial",
        "icon": "🪦",
        "area": "forgotten_catacomb",
        "level": 1,
        "desc": "Một thử thách ngắn trong hầm mộ. Mỗi ngày vào được 3 lần.",
        "enemies": ["grave_skeleton", "hollow_soldier", "ash_hound"],
        "bonus_souls": 80,
        "bonus_gold": 35,
        "bonus_loot": [("iron_shard", 0.75, 1, 3), ("ember_stone", 0.18, 1, 1)],
    },
    "blackroot_hunt": {
        "name": "Blackroot Hunt",
        "icon": "🌲",
        "area": "blackroot_forest",
        "level": 4,
        "desc": "Một cuộc săn trong rừng đen. Cần mở Blackroot Forest trước.",
        "enemies": ["thorn_wolf", "lost_hunter", "root_witch"],
        "bonus_souls": 140,
        "bonus_gold": 55,
        "bonus_loot": [("blackroot_leaf", 0.85, 2, 4), ("ember_stone", 0.28, 1, 1)],
    },
}
